// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

typedef enum {
    ACQUIRE_PANEL = 0,
    TIMEBASE_PANEL,
    TRIGGER_PANEL,
    STORAGE_PANEL,
    CURSOR_PANEL,
    ABOUT_PANEL
} ctrl_panel_t;

void selectpanel(ctrl_panel_t panel);
void settings_dd_cb(lv_event_t * e);
void time_roller_cb(lv_event_t * e);
void channel_roller_cb(lv_event_t * e);
void trigger_edge_roller_cb(lv_event_t * e);
void trigger_btn_cb(lv_event_t * e);
void couple_btn_cb(lv_event_t * e);
void runstop_btn_cb(lv_event_t * e);
void single_btn_cb(lv_event_t * e);
void save_cb(lv_event_t * e);
void ref_checkbox_cb(lv_event_t * e);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_settingsel;
extern lv_obj_t * ui_topbar;
extern lv_obj_t * ui_runstopbtn;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_singlebtn;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_btnbar;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_acquirepanel;
extern lv_obj_t * ui_timebasepanel;
extern lv_obj_t * ui_Coupledesc;
extern lv_obj_t * ui_CoupleBTN1;
extern lv_obj_t * ui_CoupleBTN2;
extern lv_obj_t * ui_CoupleBTNLBL1;
extern lv_obj_t * ui_CoupleBTNLBL2;


extern lv_obj_t * ui_Timedesc;
extern lv_obj_t * ui_TimeSel;
extern lv_obj_t * ui_Voltagedesc;
extern lv_obj_t * ui_VoltageSel;
extern lv_obj_t * ui_triggerpanel;
extern lv_obj_t * ui_trigedgedesc;
extern lv_obj_t * ui_trigsel;
extern lv_obj_t * ui_trigvaluedesc;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_storagepanel;
extern lv_obj_t * ui_Timedesc1;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox3;
extern lv_obj_t * ui_Voltagedesc1;
extern lv_obj_t * ui_VoltageSel1;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_cursorpanel;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_aboutpanel;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui____initial_actions0;

extern lv_chart_series_t * ui_Chart2_series_1;

LV_FONT_DECLARE(ui_font_sourcehan20);
LV_FONT_DECLARE(ui_font_sourcehan36);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
